### ISSUE TITLE
Endpoint for all organizations

### ISSUE THREAD

**Issue by joepio** [ontola/ori_api#1]
Perhaps also add functionality so users can get only municipalities / only providences.

**Comment by rescribet** [comment]
Closed in 8eb41139ebe7df87ade35f120b84dc01807a6c30

The endpoint will be available on `https://api.openraadsinformatie.nl/v1/organizations` when the new version will be rolled out and an organization resource has been processed

**Comment by joepio** [comment]
This currently 404s

**Comment by rescribet** [comment]
The feature has been implemented, is this the appropriate repo for hosting issues?

**Comment by joepio** [comment]
Fair point

**Comment by joepio** [comment]
Still 404s, but it's not ingress this time

**Comment by rescribet** [comment]
Closing this in favour of https://github.com/ontola/ori_api/issues/4, since this feature has been implemented
