### ISSUE TITLE
Organizations endpoint returns 404

### ISSUE THREAD

**Issue by rescribet** [ontola/ori_api#4]

**Comment by joepio** [comment]
https://api.openraadsinformatie.nl/v1/organizations does seem to route to ori_api (see 'openresty' notice in the bottom), but for some reason returns a 404

**Comment by jorritb** [comment]
> https://api.openraadsinformatie.nl/v1/organizations does seem to route to ori_api (see 'openresty' notice in the bottom), but for some reason returns a 404

Last I heard @fletcher91 was working on this.

**Comment by rescribet** [comment]
Fixed
